language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-.+'
    - 'android-sdk-license-.+'